language: node_js
node_js:
- '7'
before_script: chmod 0777 ./node_modules/.bin/mocha
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_9c6402be0697_key -iv $encrypted_9c6402be0697_iv
  -in private_keys.tar.enc -out private_keys.tar -d
- tar xvf private_keys.tar
